Insurance Cost Estimator
========================================================

```{r setup}
require(knitr)
require(plyr)
require(ggplot2)
source('func.r')
```


Declare available policies:

```{r policies}

policies <- rbind(
    data.frame(policy.name='2014 CIGNA Choice Fund with HSA' , ind.deductible=1500, fam.deductible=3000, copay.pct=.80, ind.oop.max=1500, fam.oop.max=12000, premium=(186.75*2))
,
    data.frame(policy.name='2014 CIGNA OAP (PPO) Standard Plan' , ind.deductible=600, fam.deductible=1200, copay.pct=.80, ind.oop.max=600, fam.oop.max=4800, premium=(236.67*2))
,
    data.frame(policy.name='2013 CIGNA OAP (PPO) Gold Plan' , ind.deductible=600, fam.deductible=1200, copay.pct=.80, ind.oop.max=2400, fam.oop.max=4800, premium=(166.67*2))
)
policies$policy.id <- row.names(policies)

```

Declare family members:

```{r insured}
insured <- rbind(
    data.frame(Name='Parent A',  VisitBase=250,  SickRisk=0.1, CatRisk=0.01)
    ,
    data.frame(Name='Parent B' , VisitBase=500,  SickRisk=0.2, CatRisk=0.01)
    ,
    data.frame(Name='Child C' ,  VisitBase=250,  SickRisk=0.4, CatRisk=0.01)
    ,
    data.frame(Name='Child D' ,  VisitBase=250,  SickRisk=0.4, CatRisk=0.01)
    ,
    data.frame(Name='Child E' ,  VisitBase=250,  SickRisk=0.4, CatRisk=0.01)
      ,
    data.frame(Name='Child F' ,  VisitBase=250,  SickRisk=0.4, CatRisk=0.01)
        ,
    data.frame(Name='Child CG' ,  VisitBase=250,  SickRisk=0.4, CatRisk=0.01)
)
```


Run a year with _n_ iterations:

```{r func.yr}
n <- 500
costs <- yearcosts(insured, n)
head(costs)
subset(costs, cost.iteration == 1)
scenarios <- explode.scenarios(costs, policies)
head(scenarios)
str(scenarios)
subset(scenarios, cost.iteration == 1)
results <- calculate.family(scenarios)
head(results)
```


Measure the probability densities of the results, by policy
```{r densities}
dxy <- ddply(results, .(policy.name), summarize, dx=density(fam.net.capped)$x, dy=density(fam.net.capped)$y )
dxy <- ddply(dxy, .(policy.name), transform, qleft=quantile(dx, 0.333), qright=quantile(dx, 0.666))
dxy$ytail <- ifelse(dxy$dx <= dxy$qleft | dxy$dx >= dxy$qright , dxy$dy, 0)

```


Plot the outcomes

```{r plot.outcomes}
ggplot(results) + geom_density(aes(x=fam.net)) +
  geom_area(data=dxy,aes(x=dx,y=ytail ), fill="green",colour=NA,alpha=0.5) +
  geom_vline(aes(xintercept=fam.net.max),color='red') + 
  facet_wrap( ~ policy.name, ncol=1)

ggplot(results) + geom_histogram(aes(x=fam.net), binwidth=100) +geom_vline(aes(xintercept=fam.net.max),color='red')+ facet_wrap( ~ policy.name, ncol=1)

# combined density curve and probability histogram
ranges <- policies
# annualize the monthly premium
ranges$premium <- ranges$premium * 12
# Calculate the premium + deductible out-of-pocket baseline
ranges$dedplusprem <- ranges$fam.deductible + ranges$premium 
dummyranges <- ranges
dummyranges$premium <- 0
dummyranges$dedplusprem <- dummyranges$premium 
ranges <- rbind(dummyranges, ranges)

ggplot(results, aes(x=fam.net.capped)) +
  geom_histogram(aes(y = ..density..), binwidth=density(results$fam.net.capped)$bw) +
  geom_area(data=ranges, aes(x=premium , y=0.0015) , fill="orange", alpha=0.5) + 
  geom_area(data=ranges, aes(x=dedplusprem, y=0.0015) , fill="yellow", alpha=0.5) +
  geom_area(data=dxy,aes(x=dx,y=ytail ), fill="green",colour=NA,alpha=0.5) +
  geom_vline(aes(xintercept=fam.net.max),color='red') +
  geom_density(color="blue") +
  facet_wrap( ~ policy.name, ncol=1) +
  scale_y_continuous(limits=c(0,0.0025)) +
  scale_x_continuous("Net family costs", limits=c(0, 30000))


```

